---
title: "Final Project Codebook"
author: "Ryan Fischbach"
date: "5/13/2021"
output: 
  pdf_document:
  toc: true
  number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
```

```{r, include=FALSE}
#Install required packages
library(ggplot2)
library(leaps)
library(glmnet)
library("VIM")
library(corrplot)
library(caret)
library(mltools)
library(rpart)
library(rattle)
library(rpart.plot)
library(randomForest)
library(dplyr)
```

```{r, include=FALSE}
#Import data and get general information
kickstarterData <- read.csv("/Users/rtf/Downloads/archive/ks-projects-201801.csv")
ncol(kickstarterData)
nrow(kickstarterData)
```

```{r}
#See how many are greater than 10,000 in funding and less than 100,000
#length(which(subsetKickstarter$usd_pledged_real > 10000 & subsetKickstarter$usd_pledged_real < 100000))

#Get data greater than 10,000 funding and less than 100,000
greaterIndex = which(kickstarterData$usd_pledged_real > 10000 & kickstarterData$usd_pledged_real < 100000)
greaterData = kickstarterData[greaterIndex, ]

#Get data less than or equal to 10,000 funding and undersample
lessIndex = which(kickstarterData$usd_pledged_real <= 10000)
lessData = kickstarterData[lessIndex, ]
set.seed(42)
lessDataUndersampled = sample_n(lessData, 46358, replace=FALSE)

#Combine datasets & randomize
subsetKickstarterDownsampled <- rbind(greaterData, lessDataUndersampled)
subsetKickstarterDownsampled <- sample_n(subsetKickstarterDownsampled, nrow(subsetKickstarterDownsampled))
```

```{r, include=FALSE}
#Remove columns from data because that provide little/redundant information for prediction
subsetKickstarter = subsetKickstarterDownsampled[c(-1,-2, -3, -6, -7, -8, -9, -10, -13)]

#one hot encode general category, country, and status to allow for each relationship to be understood
dmy <- dummyVars("~ .", data = subsetKickstarter)
subsetKickstarter2 <- data.frame(predict(dmy, newdata = subsetKickstarter))
```

```{r, include=FALSE}
aggr_plot <- aggr(subsetKickstarter2, col = c("navyblue", 'red'), numbers=TRUE, sortVars=TRUE, labels=names(subsetKickstarter2), cex.axis=0.7, gap=3, ylab=c("Histogram of missing data", "Pattern"))
```

```{r, warning = F, message=F}
ggplot(kickstarterData, aes(x=usd_pledged_real)) + geom_histogram() + labs(title="Figure 2.1: Distribution of Pledged Dollars", x = "Amount of Funding Raised (USD)", y = "Number of Campaigns")
```

```{r, warning = F, message=F}
ggplot(subsetKickstarter, aes(x=usd_pledged_real)) + geom_histogram() + labs(title="Figure 3.1: Distribution of Pledged Dollars", x = "Amount of Funding Raised (USD)", y = "Number of Campaigns")
```

```{r}
set.seed(42)
suppressMessages(library(rpart))
#Grow the tree
tree.pledge <- rpart(usd_pledged_real ~ . - usd_pledged_real, method="anova", data=subsetKickstarter, cp = 0.02)

#print output to determine best number of splits
#print(tree.pledge$cptable)

#prune tree
prune.tree.pledge <- prune(tree.pledge, cp=tree.pledge$cptable[6, "CP"])

#Visualize tree
fancyRpartPlot(prune.tree.pledge, sub="", cex=0.8, main="Figure 3.2: Tree to Model Dollars Pledged (USD)")
```

```{r}
set.seed(42)

#Estimated MSE for root (training MSE)
MSE_root <- mean(((subsetKickstarter$usd_pledged_real) - mean((subsetKickstarter$usd_pledged_real)))^2)

#Root node error times xerror (xerror: column times the RNE gives us 10-fold CV estimated test MSE)
testRMSE_pruned = sqrt(MSE_root * tree.pledge$cptable[5, "xerror"])

#Root node error times relerror (relerror: column times the RNE gives us training RMSE)
trainingRMSE_pruned = sqrt(MSE_root * tree.pledge$cptable[5, "rel error"])
```

```{r, warning=FALSE, include = FALSE}
suppressMessages(library(caret))

#Find variable importance
varImp(prune.tree.pledge, compete = FALSE)
```

```{r, include = FALSE}
predictions <- predict(prune.tree.pledge)
#create a scatterplot comparing truth and predictions
dev.new()
ggplot(subsetKickstarter, aes(x=predictions, y=usd_pledged_real)) + geom_point() + geom_abline(intecept = 0, slope = 1)

```

```{r}
ggplot(subsetKickstarter, aes(x=backers, y = usd_pledged_real)) + geom_point(color = "purple") + labs(title="Figure 4.1: USD Pledged Vs. Backers", x = "Number of Backers", y = "Amount Pledged in USD")
```

```{r}
ggplot(subsetKickstarter, aes(x=usd_goal_real, y = usd_pledged_real)) + geom_point(color = "blue") + labs(title="Figure 4.2: USD Pledged Vs. USD Goal", x = "Campaign Goal in USD", y = "Amount Pledged in USD")
```

```{r}
set.seed(42)
#Create design matrix
XD <- model.matrix(usd_pledged_real ~ . - usd_goal_real, data =subsetKickstarter)

#Fit lasso model
cv.out <- cv.glmnet(XD[, -1], subsetKickstarter$usd_pledged_real, alpha = 1, lambda = seq(from = 0, to = 1000, by = .5) )
plot(cv.out, main="Figure 4.3: MSE vs Lambda Value, 10-fold CV")
```

```{r, include=FALSE}
#Find RMSE
sqrt(min(cv.out$cvm))

#Find min lambda
cv.out$lambda.min
```

```{r}
#Compute final lasso model and show coefficients
lasso.final <- glmnet(XD[, -1], subsetKickstarter$usd_pledged_real, alpha=1, lambda= cv.out$lambda.min)
#predict(lasso.final, type = "coefficients", s = cv.out$lambda.min)

Mat <- cbind(Lasso = coefficients(lasso.final))
Mat <-as.matrix(Mat)
colnames(Mat) <-c("Lasso")
Mat <- data.frame(Mat)
knitr::kable(Mat, caption="Table 4.1: Lasso Model Coefficients")
```